before_install:
- git clone -b travis `git config --get remote.origin.url` target/travis
- wget https://dl.dropboxusercontent.com/u/7897865/apache-maven-3.3.9.zip
- unzip -qq apache-maven-3.3.9.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
- rm ~/.m2/settings.xml
branches:
  only:
  - develop
env:
  global:
  - secure: pDTp3TujySuBn3IV5QzgYSsLdLHRDApm2dvKT5P8aHgLDF2tM59a5fWYuA+MiTrZdpbxsUXzxrl4l5+cQyLGI10/hu4R7uft4k46Da78xNA5REki+YU7rjCA6RXdWUuXyhLNFYPWVNt3mgi7YfsyNwRrtS3FQQZn1BOfDJ0s5Vo=
  - secure: YwWFnNl4cBEKzRiMjKlfp1VieMkWp4LGENMKzlVs7hy3TWFz4A2pJpRUX76qqWV/6h6vOqY6cogql3NCietzJbspSgwl7MkboPVXYn9HgQkPwrcdQh/h9PzsC63iOW4jyIqHzjVT36MYLYrXTvRrqdMHUjFJmObiNt1KY674d7g=
jdk:
- oraclejdk8
language: java
matrix:
- LC_ALL=C
- LC_ALL=pl_PL
- LC_ALL_zh_CN
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
script: ' if [ ${TRAVIS_PULL_REQUEST} = ''false'' ]; then mvn clean deploy --batch-mode --settings target/travis/settings.xml; else mvn clean verify --batch-mode --settings target/travis/settings.xml; fi'
sudo: false
